delayTimer=1;
lilyTimer=1;
onPlatform=false;
onLog = false;
global.startScreen=false; // in create so that text goes away immediately.
global.gameWon=false;
global.gameFail=false;
image_speed=0;
image_index=3;
delayFail=false;
delayWon=false;
